///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Git
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the GitRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("afa79195-be98-463b-90a9-a639d4d9833f")]
    public partial class GitRepository : RepoGenBaseFolder
    {
        static GitRepository instance = new GitRepository();
        GitRepositoryFolders.UntitledNotepadAppFolder _untitlednotepad;
        GitRepositoryFolders.NotepadAppFolder _notepad;

        /// <summary>
        /// Gets the singleton class instance representing the GitRepository element repository.
        /// </summary>
        [RepositoryFolder("afa79195-be98-463b-90a9-a639d4d9833f")]
        public static GitRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public GitRepository() 
            : base("GitRepository", "/", null, 0, false, "afa79195-be98-463b-90a9-a639d4d9833f", ".\\RepositoryImages\\GitRepositoryafa79195.rximgres")
        {
            _untitlednotepad = new GitRepositoryFolders.UntitledNotepadAppFolder(this);
            _notepad = new GitRepositoryFolders.NotepadAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("afa79195-be98-463b-90a9-a639d4d9833f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The UntitledNotepad folder.
        /// </summary>
        [RepositoryFolder("3bd5a24a-15c4-4079-b6a2-ccd078aa5e7d")]
        public virtual GitRepositoryFolders.UntitledNotepadAppFolder UntitledNotepad
        {
            get { return _untitlednotepad; }
        }

        /// <summary>
        /// The Notepad folder.
        /// </summary>
        [RepositoryFolder("cb86f513-5c4e-47a8-a0c4-c8f24780d847")]
        public virtual GitRepositoryFolders.NotepadAppFolder Notepad
        {
            get { return _notepad; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class GitRepositoryFolders
    {
        /// <summary>
        /// The UntitledNotepadAppFolder folder.
        /// </summary>
        [RepositoryFolder("3bd5a24a-15c4-4079-b6a2-ccd078aa5e7d")]
        public partial class UntitledNotepadAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new UntitledNotepad  folder.
            /// </summary>
            public UntitledNotepadAppFolder(RepoGenBaseFolder parentFolder) :
                    base("UntitledNotepad", "/form[@title='Untitled - Notepad']", parentFolder, 30000, null, true, "3bd5a24a-15c4-4079-b6a2-ccd078aa5e7d", "")
            {
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", 30000, null, "682b5d52-9a5d-45a1-b5e8-e687321ab698");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3bd5a24a-15c4-4079-b6a2-ccd078aa5e7d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3bd5a24a-15c4-4079-b6a2-ccd078aa5e7d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("682b5d52-9a5d-45a1-b5e8-e687321ab698")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("682b5d52-9a5d-45a1-b5e8-e687321ab698")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

        /// <summary>
        /// The NotepadAppFolder folder.
        /// </summary>
        [RepositoryFolder("cb86f513-5c4e-47a8-a0c4-c8f24780d847")]
        public partial class NotepadAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _dontsaveInfo;

            /// <summary>
            /// Creates a new Notepad  folder.
            /// </summary>
            public NotepadAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Notepad", "/form[@title='Notepad']", parentFolder, 30000, null, true, "cb86f513-5c4e-47a8-a0c4-c8f24780d847", "")
            {
                _dontsaveInfo = new RepoItemInfo(this, "DontSave", "?/?/element[@instance='1']/button[@text='Do&n''t Save']", 30000, null, "2015bba5-8205-40e4-a7ab-d46dcc6849e4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cb86f513-5c4e-47a8-a0c4-c8f24780d847")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cb86f513-5c4e-47a8-a0c4-c8f24780d847")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DontSave item.
            /// </summary>
            [RepositoryItem("2015bba5-8205-40e4-a7ab-d46dcc6849e4")]
            public virtual Ranorex.Button DontSave
            {
                get
                {
                    return _dontsaveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DontSave item info.
            /// </summary>
            [RepositoryItemInfo("2015bba5-8205-40e4-a7ab-d46dcc6849e4")]
            public virtual RepoItemInfo DontSaveInfo
            {
                get
                {
                    return _dontsaveInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}